### ISSUE TITLE
[Feat] Static Configuration

### ISSUE THREAD

**Issue by hjkatz** [WTFender/aws-sso-extender#100]
### Description

It would be really handy if we could share static configurations that we can upload into our extension for things like favorites, colors, naming patterns, etc...

**Comment by WTFender** [comment]
@hjkatz I'll consider adding a button to make this easier, but you can share the customizations from your JSON config.

Export/Edit your config and look for `users[].custom` - this has all of your profile customizations that you can share with team members; or if you just want to share your account labels/colors/IAM Roles, use `users[].custom.profiles`.

The `p-uniqueId` is your AWS SSO permission set ID if you wanted to create these yourself.

```json
"profiles": {
  "p-69d38fe42417a8ab": {
    "color": "187df0",
    "favorite": false,
    "label": "CustomProfileName",
    "iamRoles": []
  },
  "p-8b6131c3c74df7fd": {
    "color": "ff004d",
    "favorite": false,
    "label": "CustomProfile2",
    "iamRoles": []
  }
},
```


<img width="400" alt="image" src="https://github.com/WTFender/aws-sso-extender/assets/12001399/230691f1-122c-4c5d-b513-bfec1b2aedd8">

**Comment by hjkatz** [comment]
Ah thank you! I did end up finding this section but I wasn't sure what the `p-###` ids were referencing and I didn't want to rely on them.

What would be amazing is a button that just let's you configure the `users[].custom.profiles` section and does the reverse mapping for you going back when you hit "save", but I understand that's more involved.

Thanks for the pointers and thanks for the great extension!
