### ISSUE TITLE
Profile width should be dynamic

### ISSUE THREAD

**Issue by hjkatz** [WTFender/aws-sso-extender#101]
### Extension Version

1.7.6

### Description

See image: 
![image](https://github.com/WTFender/aws-sso-extender/assets/2234516/b88e722b-939e-41ab-b4e1-181a3dc288de)

It would be lovely if the profiles or full extension window could dynamically expand (or just be a bit larger) for longer named profiles.

### Browsers

Chrome

### OS

Mac

**Comment by WTFender** [comment]
Agreed, the UI is a bit of a mess & not responsive. I have some major reworks coming, but can't promise it soon.

I'd recommend renaming those longer profiles, but also realize that's not feasible for 100s of accounts.

**Comment by hjkatz** [comment]
We were able to work around this for now with profile labels and unique colors for our users.

Thanks for this extension, it's a real lifesaver as I work to convert our org to SSO.

**Comment by WTFender** [comment]
I've made this a little bit better... the profile names will expand a bit wider if no IAM role exists & collapse a bit if one does. I think this is as good as I can get it; those names can be up to 64 characters & labels are the better solution IMO.

![expand role names](https://github.com/WTFender/aws-sso-extender/assets/12001399/d9fd48c4-91a5-4f3e-bd78-5947ca1e5839)

**Comment by davidebonavita** [comment]
Hi
in my case the profile name are not expanding when I don't select the IAM roles. It will just make the Profile section smaller

<img width="479" alt="image" src="https://github.com/WTFender/aws-sso-extender/assets/11682646/07f0393d-c85b-4cd0-aea6-d546d8c5d574">

<img width="406" alt="image" src="https://github.com/WTFender/aws-sso-extender/assets/11682646/5f04b1c1-b160-4f6b-8239-820eb83baa9f">
