### ISSUE TITLE
Tab switch prevents sessions from refreshing

### ISSUE THREAD

**Issue by jutley** [WTFender/aws-sso-extender#113]
### Extension Version

1.8.2

### Description

I previously used this plugin with AWS SSO Containers. I disabled that to try using this plugin's built-in container support, but it is breaking some pretty basic use cases for me.

I often have a handful of tabs open for an SSO profile for many days. Today is my second day using the container support in this plugin, and I can't seem to keep those existing tabs and refresh my SSO session.

Every time I click on the profile, it brings me to an existing tab, and this tab says that I need to re-authenticate. That totally makes sense, but I don't know how I can refresh that session! Every time I try to log in via this plugin, it just takes me back to that tab without logging in.

When using both plugins, there is no tab switching capability. Signing in would open a new tab in the container, which would refresh the session. Then I can close that tab, go to my existing tabs, refresh, and I can pick up where I left off the previous day. This plugin doesn't seem to have any way to disable the tab switching functionality. Being able to turn it off entirely or just for a single usage of the plugin's UI would do the trick.

### Browsers

Firefox

### OS

Mac

**Comment by WTFender** [comment]
No bueno, I'll look into this.

Need to figure out how to update the containers with the refreshed session tokens or potentially recreate the container.
