### ISSUE TITLE
When Profile Label has been overridden, the Sort does not seem to honor the override value

### ISSUE THREAD

**Issue by dhoffman-vertex** [WTFender/aws-sso-extender#114]
### Extension Version

1.8.2

### Description

When Sorting by Profile, the sort works fine - unless you override the Profile Label.  If you do that, it seems to continue to sort by the original label.

This may be by design in which case this would be a feature request, but it functions in a way I would not expect it to.

Expectation would be that if you override the value of the Profile Label, Sorting by Profile would use the override value rather than the original value for the sort.

The actual profile of all of these is identical, but I overrode the values because the full name of the account is not displayed.  This is sorted by Profile Ascending.

<img width="329" alt="image" src="https://github.com/WTFender/aws-sso-extender/assets/81321184/f903dc90-e879-4082-b9ac-0a383da26024">

### Browsers

Chrome

### OS

Mac

**Comment by WTFender** [comment]
Good catch & thanks for the details!

1.8.7 will now use your profile labels or name when sorting.
