### ISSUE TITLE
UI No longer updates

### ISSUE THREAD

**Issue by Luke-Edwards** [WTFender/aws-sso-extender#129]
### Extension Version

1.8.10

### Description

It would appear that once you make a large amount of changes to labels/favorites etc. you can no longer make any more. For example updating a profiles label/colour will have no affect and staring a profile will also have no affect.

This does not seem to be version specific as i have had this on an older version also

### Browsers

Firefox

### OS

Mac

**Comment by WTFender** [comment]
@Luke-Edwards do you know approx how many profiles or customized profiles you have? (dozens, hundreds)

Export your config first and then try unchecking the below setting.

Unchecking this setting forces extension data to be stored in your local browser vs sync'd across browsers you're signed into. The local storage limit is much higher.

<img width="500" alt="Screenshot 2024-03-27 at 4 08 14 PM" src="https://github.com/WTFender/aws-sso-extender/assets/12001399/7eb7767a-9418-4ee5-b4ae-9aae92ab4ab3">

**Comment by Luke-Edwards** [comment]
25-30 customised profiles, and about 30 more hidden profiles if they count as customised also. Total amount of profiles combined just over 100

Unchecking solved the issue though, thanks!
