### ISSUE TITLE
"Select SSO profiles" select doesn't handle long account names

### ISSUE THREAD

**Issue by syphernl** [WTFender/aws-sso-extender#133]
### Extension Version

1.8.11

### Description

The "Select SSO profiles" selector doesn't properly handle long entries, causing it to overflow and makes the text very hard to read.

![image](https://github.com/WTFender/aws-sso-extender/assets/639906/95e6e166-0018-423c-a8a4-275fa8110d4d)

In this case the whole item is 70 characters of which 35 characters for the account name and 13 characters for the role.

### Browsers

Chrome

### OS

Linux

**Comment by WTFender** [comment]
This isn't perfect, but I removed the account nickname for now.

![image](https://github.com/WTFender/aws-sso-extender/assets/12001399/46f4bfea-9636-40f2-a6a6-777184aa7e27)
