### ISSUE TITLE
Logging in to IAM Role shows SSO Console label instead of IAM Console label

### ISSUE THREAD

**Issue by syphernl** [WTFender/aws-sso-extender#134]
### Extension Version

1.8.11

### Description

When assuming an IAM Role the following happens:

- SSO Login to the account the role is attached to
- The header (and footer) color reflects that of the account signed into (and the label is updated)
- The SwitchRole UI is shown and the Display name field gets populated with the name of the SSO account instead of IAM Role and gets submitted
- Role is assumed, name of the SSO account is shown instead of that of the assumed role
- No coloring is applied to the header/footer

I assumed the "IAM Console Label" would be used in this case, not the SSO Console Label.

![image](https://github.com/WTFender/aws-sso-extender/assets/639906/9e6350e9-bc69-46e9-a1c2-2799291abd4b)

### Browsers

Chrome

### OS

Linux

**Comment by WTFender** [comment]
Thanks for the details! I fixed a bug where the SSO label format was applying for IAM roles.

Although, I wasn't able to reproduce the color part - the correct colors always appeared.
