### ISSUE TITLE
Request: option to use current tab instead of opening a new one when switching

### ISSUE THREAD

**Issue by zachbtp** [WTFender/aws-sso-extender#142]
### Description

Sometimes you wind up on an aws service but in the wrong profile, would be nice to just replace the current page instead of always opening a new browser tab. Checkbox in settings would do it (default to current behavior, obvs).

**Comment by WTFender** [comment]
I added a setting for this, let me know if you run into any problems.

![image](https://github.com/WTFender/aws-sso-extender/assets/12001399/d63a733c-8ba9-46c6-8788-1fce67266266)
