### ISSUE TITLE
How to import saved settings?

### ISSUE THREAD

**Issue by yermulnik** [WTFender/aws-sso-extender#150]
### Extension Version

1.8.15

### Description

I can see button to export setting, but I can't seem to find the import button 🤷🏻 Please advise.
![image](https://github.com/WTFender/aws-sso-extender/assets/1274789/b16e2eba-d450-46be-b6ba-ed9a61178c26)

### Browsers

Firefox, Chrome

### OS

Linux

**Comment by WTFender** [comment]
@yermulnik Hah - I should probably add a button to upload a file :).

For now, go to JSON and copy/paste your config.

**Comment by yermulnik** [comment]
> @yermulnik Hah - I should probably add a button to upload a file :).

That would be great as restoring config puzzled me and eventually I had to configure it on another browser manually.

> For now, go to JSON and copy/paste your config - set the JSON editor to "text" mode.

I tried that editor, though it's a way far from obvious that I can paste over the top of the existing data (I didn't try though. Is it just paste? 🤔).

**Comment by WTFender** [comment]
@yermulnik it's definitely not obvious :).

Set the editor to "text" mode and you can select/copy/paste.

![image](https://github.com/user-attachments/assets/d6b991be-dddc-470c-926f-762c66da0257)

**Comment by yermulnik** [comment]
Thanks for the hints 👍🏻
Closing as resolved, whilst would definitely look forward for you to be adding "Upload file" butting 😺
