### ISSUE TITLE
Add Feature to Open AWS Console in Private Tab

### ISSUE THREAD

**Issue by sergiovm** [WTFender/aws-sso-extender#152]
### Description

I propose adding a feature to allow users to open the AWS Console in a private tab. This enhancement will enable users to manage multiple AWS accounts simultaneously without session conflicts. Currently, opening multiple AWS accounts requires continuous logging in and out, which is cumbersome. By enabling a private tab option, users can seamlessly switch between accounts, improving efficiency and user experience.

**Comment by WTFender** [comment]
@sergiovm I'm assuming you're on chrome. I could add a setting to open profiles in incognito mode, but this would only allow you to open 2 consoles at a time, 1 in incognito and 1 in normal.

If you need to open more than 2 consoles, I recommend checking out the firefox version of this extension that uses tab containers.

**Comment by sergiovm** [comment]
@WTFender thanks for your reply. In fact, I'm using Safari but I guess it behaves like Chrome in this regard. Thanks for the tip, I'll try Firefox with this extension.

**Comment by kamatsuoka** [comment]
@WTFender In safari, aren't incognito tabs independent of each other? It seems like you should be able to have multiple incognito tabs, each with its own separate aws login

**Comment by WTFender** [comment]
@kamatsuoka thank you - I'm light on safari knowledge! Maybe I can pass the SSO session to private tabs.

The safari extension is just a port of the chrome one for now, so I'm going to close this, but will think about it as more safari issues pop-up.
