### ISSUE TITLE
Safari app not available in certain regions?

### ISSUE THREAD

**Issue by AlastairMiller** [WTFender/aws-sso-extender#156]
### Extension Version

1.3.4

### Description

Hi,

This SSO extension is just what I am looking for but unfortunately am unable to install the Safari version from the UK app store. Is this an intentional restriction?

FYI, I also cannot select Safari from the `Browsers` option in the bug report.

Thanks.

![image](https://github.com/user-attachments/assets/389d7b15-1f78-44e3-9e0a-73c7ef67ac4d)

### Browsers

Chrome

### OS

Mac

**Comment by WTFender** [comment]
Hey, my Apple developer sub expired and I just renewed it - that’s probably
the problem.

Check again soon / tomorrow.

Also, I’ll publish the latest version soon - safari is a bit behind.

**Comment by AlastairMiller** [comment]
@WTFender Thanks, can access it now :)

**Comment by cdanyl** [comment]
Hello,
Same problem cannot install this app from France region 

<img width="314" alt="Image" src="https://github.com/user-attachments/assets/8ebe6328-1226-412c-9c80-7318e36bad8a" />

**Comment by janjanneck7777** [comment]
@WTFender This is still an issue for Safari. Could you please have a look?
