### ISSUE TITLE
AWS styling changes have broken extension

### ISSUE THREAD

**Issue by chrisgilbert** [WTFender/aws-sso-extender#169]
AWS Seem to have changed the styling today, just as I was trying to get your extension to work!

It's not changing the AWS menu for me - I get the following error in the console:

```
aws-console.js:1 Uncaught (in promise) Error: Timeout: Element not found with selector "#menu--account"
    at aws-console.js:1:21039
```

I think it's this line:

https://github.com/WTFender/aws-sso-extender/blob/5846ebea2c1d67f331d1904c39056e9fe543f46f/src/entry/aws-console.ts#L111

`#menu--account` probably needs to be switched to `#nav-usernameMenu` I guess.

**Comment by WTFender** [comment]
@chrisgilbert Thanks for letting me know! Looks like they made some slight tweaks, I'll have a fix out soon.

**Comment by WTFender** [comment]
There were some subtle HTML changes to the AWS console menu that messed up how I'm scraping the account info. Some pages use the updated HTML and some still use the old format.

Let me know if you see anything else odd.
