### ISSUE TITLE
Custom labels and colors don't always apply, and once applies it always shows the same, independent of account/login

### ISSUE THREAD

**Issue by renataogarcia** [WTFender/aws-sso-extender#20]
It doesn´t always apply the custom values and once applied it never changes. E.g. Log to Staging, then log into Prod and it still shows Staging in the header, even though it is a different environment.

**Comment by WTFender** [comment]
This is fixed in v1.2.5 - please let me know if it's still happening.

I wasn't checking the console accountId; it was applying the values for the first matching roleName.

**Comment by renataogarcia** [comment]
Works like a charm! Thanks!
