### ISSUE TITLE
Suggestion: UX Enhancements

### ISSUE THREAD

**Issue by rst515** [WTFender/aws-sso-extender#32]
Love this tool, using it regularly, thank you for creating it 😊

Some suggestions that might be helpful for users:
 - be able to re-order the accounts in the list to a custom order
 - be able to choose to have the favourites view ⭐️ when opening the app

Thanks!

**Comment by WTFender** [comment]
Thanks for the feedback! 

It's still early days, but improvements to the profile list and generally polishing the UI are next up!

**Comment by WTFender** [comment]
Your favorites should open by default now (if you have favorites) and there is a setting if you want to force it to show the profiles instead.

Still working on improvements to the account/profile list :).

**Comment by allank-fd** [comment]
Thanks for the great extension, A "compact style" view would be very appreciated for the account/profile listings

**Comment by REBELinBLUE** [comment]
Thanks for this extension, it might just save my sanity!

I have a minor suggestion, if the extension could show which account you are currently logged into it would be great, since the AWS Console UI only shows the account ID

**Comment by WTFender** [comment]
@allank-fd not specifically a compact view, but in the latest version, you can uncheck these items to get a smaller view. The scale of everything has generally been reduced too.
<img width="392" alt="image" src="https://github.com/WTFender/aws-sso-extender/assets/12001399/316062b3-6bce-4102-ba74-8b758509a4b9">

**Comment by WTFender** [comment]
@rst515 in the latest version you can sort the profile list or drag & drop.

**Comment by allank-fd** [comment]
Thanks for the effort on this @WTFender , looks great!
