### ISSUE TITLE
Custom colour and labelling not working on AWS website

### ISSUE THREAD

**Issue by rst515** [WTFender/aws-sso-extender#33]
All was working great but today neither the custom colouring of the header and footer, nor the custom labels are working.  Would love to see these again 😁

Thanks 
😊

**Comment by WTFender** [comment]
Oooh I’ll check this out.

Are you on Firefox or chrome?
Does a fresh install fix it?

I think there is some potential for user configs to get messed up between
versions 🔎.

**Comment by WTFender** [comment]
I was able to replicate this. You should get updated to 1.3.4 in the next day; let me know if that fixes things.

**Comment by rst515** [comment]
It's working again today 😁
Thank you so much! 😊⭐️
