### ISSUE TITLE
Accounts list not updated, favorites not working properly

### ISSUE THREAD

**Issue by djablonski-moia** [WTFender/aws-sso-extender#37]
### Extension Version

1.4.0

### Description

After the latest update to v1.4.0, new accounts being added do not show up in the accounts list anymore (but they do on the AWs start page). Also, adding Accounts to `Favorites` rarely works as intended. Most times, the star is immediately de-selected again in the accounts list, when trying to add an account as Favorite.

### Browsers

Firefox

### OS

Linux

**Comment by WTFender** [comment]
@djablonski-moia If you don't mind, could you take a screenshot of what permissions your extension currently has?

<img width="727" alt="Screenshot 2023-05-31 at 10 22 54 AM" src="https://github.com/WTFender/aws-sso-extender/assets/12001399/d5e03aae-d879-4c4d-9f53-d5d3b3d9c63a">

**Comment by WTFender** [comment]
I'm not able to reproduce the account list issue, but do think I caused this with all the permission changes recently.

The profile/account list should get updated in the extension when you visit the AWS SSO page. I'm assuming that the permissions were messed up between version upgrades and it can't grab the new accounts when you're on this page.

Unfortunately, I can't reproduce the favorite issue either - has that ever worked properly for you?

If you're comfortable exporting your user config and sending it to me (there is nothing sensitive in there except your AWS account IDs, role names, etc.), I can look into this a bit more. Paste it here or email wtfender.cs<at>gmail.com

**Comment by djablonski-moia** [comment]
Thanks for the quick response @WTFender!
Here are the current permissions:
![image](https://github.com/WTFender/aws-sso-extender/assets/49818625/db99fb87-7e2c-479e-88b4-a8e0a5c3cba0)
My user config will follow later (and via email, too large for here with > 100 accounts)

**Comment by WTFender** [comment]
Woah that’s a lot of accounts. We may be running into storage limits; which
would make sense why changes aren’t saving. I’ll do some bulk testing today.

**Comment by WTFender** [comment]
I was able to reproduce and fix this I believe, but let me know if it persists for you.
