### ISSUE TITLE
Suggestion: Improve UX

### ISSUE THREAD

**Issue by marcelmindemann** [WTFender/aws-sso-extender#4]
Hey WTFender,

thanks a lot for this extension, I have just tried it out and it eases the pain of AWS SSO's UX a lot. I am 80% back to my previous workflow with AWS Extend Switch roles.

However, theres a few improvements that could improve this extensions user experience a lot:
* Preferably, the search field would already have focus when opening the extension so that the user can start typing immediately.
* Some keyboard shortcuts to select the link from the list of results would be great. I am already able to quickly select the first link by pressing `<Tab>`, but selecting other links is cumbersome because the focus jumps from link to edit button.
* Support fuzzy search - there's a few good JS libraries out there already that could make the search much more efficient with little overhead

Thanks again for your time, I hope you take this as what it is: well-meant, constructive suggestions.

**Comment by WTFender** [comment]
Thanks for the feedback!
All 3 suggestions make sense and I'll see what I can get out in the next version this week.

**Comment by WTFender** [comment]
You should get auto-updated to version `1.1.6` later today.

- Search box is autofocused by default
- Press Tab to drop down to your profile list from the search box (Tab x2 on Firefox... bug), up/down arrows to navigate, enter to open. There's also a hotkey (Ctrl+Shift+F) to open the popup/search.

For the search... I'm not going to implement fuzzy searching right now. I may add it as an option later on, but I want there to be accuracy by default. To that point, I've included some hidden fields for each profile that you can search against, such as the profile IDs and descriptions (something an admin might find useful for troubleshooting).
