### ISSUE TITLE
Color for the AWS console is not being set until I click on extension icon

### ISSUE THREAD

**Issue by ardaozceviz** [WTFender/aws-sso-extender#43]
### Extension Version

1.4.4

### Description

The colors set for the different accounts within the extension are not being reflected on the actual AWS console. The correct color is reflected only when you click on the extension icon after being redirected to AWS console.

**Steps to reproduce**
1. Assign a color for an account form the extension.
2. Click on the hyperlink from the extension which you set the color.
3. You will be redirected to AWS consoloe with the default color (not the one you selected from the extension).
4. Now, click on the extension icon on the browser and see the correct color will be set.

### Browsers

Firefox

### OS

Mac

**Comment by WTFender** [comment]
I’ll check this out later today.

This behavior typically means the extension doesn’t have permissions to run
on the console URL.

Could you take a screenshot of your extension permissions?

**Comment by ardaozceviz** [comment]
Hey, thanks a lot. It was like you said, due to missing permission. Now it works!
