### ISSUE TITLE
Safari Support

### ISSUE THREAD

**Issue by jan-xyz** [WTFender/aws-sso-extender#44]
### Description

This is a really nice plugin! Is there any plan to add Safari support? What would be needed to support it? I would also be happy to support in it.

**Comment by WTFender** [comment]
Thank you!

I think the biggest hurdle is that this extension uses [webextension-polyfill](https://github.com/mozilla/webextension-polyfill) to abstract the differences between chrome & firefox browser API calls.

It looks like Apple provides some tools for running a non-Safari extension on Safari, but I anticipate I'd need to remap all of those browser API calls to something safari-compatible. I'm not sure that is realistic.

Let me do a little more research before I say no, but it's not something I'm super familiar with.

**Comment by WTFender** [comment]
I was able to get most things working - although there's a lot of cosmetic bugs. I'll figure out how to get it published to the app store soon.

If you're feeling bold... you can run `npm run port:safari` to build the extension in xcode and open in safari. You'll need to 'Allow unsigned extensions' in Safari.

<img width="1440" alt="image" src="https://github.com/WTFender/aws-sso-extender/assets/12001399/93455eec-964a-4af8-a66c-1c7edce62e37">

**Comment by jan-xyz** [comment]
This was fast! I didn't even get the chance to contribute! Thank you so much! I got it to work right away from the branch! I will be out of the office until Monday and will check it more thoroughly then.

**Comment by jan-xyz** [comment]
I had the chance today to test it thoroughly and so far I couldn't find any problems apart from the missing icons that you also already found.

**Comment by WTFender** [comment]
I fixed up some of those small issues and submitted this to the app store.

It's not approved yet, but expect to see it here soon:
https://apps.apple.com/us/app/aws-sso-extender/id6450935274

**Comment by WTFender** [comment]
@jan-xyz [app store listing](https://apps.apple.com/us/app/aws-sso-extender/id6450935274) is live now.

**Comment by jan-xyz** [comment]
Thank you for the fast pace! I will give it a spin tomorrow! Any way to buy you a coffee? ❤️ ☕ ?

**Comment by WTFender** [comment]
I added a sponsor button to the repo, but no need - I appreciate the feedback and interest!
