### ISSUE TITLE
Enable user to choose precisely the same color again in color picker

### ISSUE THREAD

**Issue by rst515** [WTFender/aws-sso-extender#48]
### Description

Great app, love it 😁

Would be great to enable user to choose precisely the same color again if they wish, perhaps by entry of text hex color values in the color picker (e.g. #1a7dbe)?  😊🎨

Thanks!

**Comment by WTFender** [comment]
Makes sense - I'll see what I can do.

As a workaround, you can copy/paste the value in your user config.

In your user config, scroll down to `users[].custom.profiles` and you should be able to copy/paste the color for each profile.

<img width="596" alt="image" src="https://github.com/WTFender/aws-sso-extender/assets/12001399/409d0bae-3cca-4acb-bed5-7edb6c4cf3d9">

**Comment by WTFender** [comment]
Hoping to get a new profile editor out this week that can help with this.

![Screenshot 2023-07-16 205933](https://github.com/WTFender/aws-sso-extender/assets/12001399/eedc3773-17db-4dc3-814c-815dae76ab60)
