### ISSUE TITLE
CSS/Font issue?

### ISSUE THREAD

**Issue by morganhowarth-fd** [WTFender/aws-sso-extender#62]
### Extension Version

1.6.0

### Description

Since 1.6.0, I've noticed that the font (and potentially CSS of the table?) is a little off. Is this intentional?

Not a huge deal as the extension is still fully useable!

PS: would be nice to have one row per account, with multiple buttons for each role rather than 1 row = 1 profile/role!

<img width="631" alt="image" src="https://github.com/WTFender/aws-sso-extender/assets/54585360/2c8c3668-1fa8-4380-a1fc-4e39b4a58073">

### Browsers

Firefox

### OS

Mac

**Comment by REBELinBLUE** [comment]
Same on Safari but looks fine on Chrome

**Comment by WTFender** [comment]
Thanks all! Just released a fix.

**Comment by WTFender** [comment]
@morganhowarth-fd more is in the works on the profile list, to include grouping; unfortunately had to take a couple steps back before moving forward.
