### ISSUE TITLE
AWS icon is too large

### ISSUE THREAD

**Issue by svdgraaf** [WTFender/aws-sso-extender#65]
### Extension Version

1.6.1

### Description

I think the default AWS icon has been updated, and it no longer fits the view nicely. I think it has extra widespace now:

`https://static.global.sso.amazonaws.com/app-03e8643328913682/icons/default.png`
![Default icon](https://static.global.sso.amazonaws.com/app-03e8643328913682/icons/default.png)

This results in a weird wide column for the images in the extension:
![Screenshot 2023-08-31 at 15 22 31](https://github.com/WTFender/aws-sso-extender/assets/19777/0a1d5216-b829-4d1d-a948-cf89ca34893d)

### Browsers

Chrome

### OS

Mac

**Comment by svdgraaf** [comment]
btw, I think this might also be the reason why the accounts are being truncated here for this issue: https://github.com/WTFender/aws-sso-extender/issues/64

**Comment by WTFender** [comment]
I agree the width isn't ideal; I'll get this fixed up with the other width issue.

In case it helps, you can uncheck the icon from showing temporarily.
<img width="509" alt="image" src="https://github.com/WTFender/aws-sso-extender/assets/12001399/107c0df2-4517-4735-aed3-393609186b13">

**Comment by WTFender** [comment]
Trimmed the icons in the latest version.
