### ISSUE TITLE
Setting a custom icon

### ISSUE THREAD

**Issue by svdgraaf** [WTFender/aws-sso-extender#66]
### Description

I tried updating the json config with my own custom icon. I would expect that to work, but the manifest file limits the icons to only be on a specific domain. I can see why.

I would like to override the default given icon with my own icon though, perhaps by adding an `icon` field to the `users/custom/profiles` section? A url to a public image should suffice I think.

**Comment by WTFender** [comment]
I'm trying to stay away from retrieving dynamic data outside of the AWS SSO page; which I think is important to keep things secure. I don't love that it's requesting the app images already.

In lieu of a fetching a remote image, how would you feel about unicode icons or an upload button?

**Comment by Elevating7734** [comment]
I can't speak for @svdgraaf, but I'd be good with Unicode—anything that allows me to distinguish different accounts visually.

**Comment by WTFender** [comment]
@Elevating7734 @svdgraaf @ncs-alexhoward

You can set a unicode icon now & it will match the profile color.

There's picklist of icons and you can mess with the JSON if you're brave.

![icons](https://github.com/WTFender/aws-sso-extender/assets/12001399/bba4061c-46b9-4cfa-aced-3ffe8174fb1b)
