### ISSUE TITLE
Custom color change for aws console in other languages

### ISSUE THREAD

**Issue by keiyow** [WTFender/aws-sso-extender#67]
### Description

Hi
Custom color changes in the AWS console do not appear to work for languages such as Japanese, Chinese, Spanish, etc.

**Comment by WTFender** [comment]
I'll look into this. The extension looks for text snippets on the page in order to identify the right html elements; should be easy to support.

**Comment by WTFender** [comment]
Should be fixed now, thanks for letting me know.

**Comment by keiyow** [comment]
Thank you for responding so quickly.
I was able to switch the color of the AWS console!
