### ISSUE TITLE
Option to open in a specific tab container

### ISSUE THREAD

**Issue by SathyaBhat** [WTFender/aws-sso-extender#70]
### Description

Would be nice if I could assign a specific tab container to an account, or when I click on it, open in the same tab. 

I typically am logged into multiple accounts separated by tab containers, right now clicking on an account opens the account in a new tab and that logs me out of the account I have opened.

**Comment by WTFender** [comment]
In 1.6.4, clicking on a profile will focus any already open container tabs and there is a green indicator in the profile list showing you which profiles are currently open.

Also, the profiles will re-use the same container, so if the tab isn't open, but the container already exists, it will open a new tab with the existing container.

**Comment by SathyaBhat** [comment]
Thanks. It works well!

**Comment by davidebonavita** [comment]
Hello @WTFender sorry to revive such an old thread. With the current behaviour (re-using the same container) once the login has expired after X hours I'm not able to login again clicking on the link from the extension. I either need to login manually from a container tab or close all the tabs. Only in this case the extension will initiate the login process.
