### ISSUE TITLE
Isn't reutilizing containers with same name anymore

### ISSUE THREAD

**Issue by allanviana-logcomex** [WTFender/aws-sso-extender#74]
### Extension Version

1.6.4

### Description

Before last update, opening a role using Firefox Containers option created a new container when doesn't existed one with the same "SSO Console Label" as name.
Now, everytime I open a role, a new container is created even when exist a container with that name. This leave a lot of containers with the same name and I have to manually delete each one.

Besides that, I used to color containers with the same color as the roles, to have visual feedback of what is opened, but in that way isn't possible anymore.

### Browsers

Firefox

### OS

Windows

**Comment by WTFender** [comment]
Ah - thanks for this report!

I introduced a bug in the last version that caused the extension to not properly re-use containers. Should be fixed shortly.

I've thought about trying to sync the colors for the profiles & containers, but firefox is pretty limiting with the color & icon selection; haven't found the right way to go about it yet.

**Comment by allanviana-logcomex** [comment]
Ow, thanks for the good job. I can confirm that is working as before. :)

About the colors, I just commented to give a scenario to explain and justify how I use.
Would be nice if was a auto color sync based on the color we choose to role, maybe calculating the closest Firefox color based on what Hex was chosen? I think that can be simple to do and there could be an option to turn this on for those who don't want it.

Anyway, thanks again, that extension helps too much. :)
