### ISSUE TITLE
HTTP 429 Errors and failed logins

### ISSUE THREAD

**Issue by gomibushi** [WTFender/aws-sso-extender#77]
### Extension Version

1.6.6

### Description

I'm getting more of these now. I think it started around 1.6.0/sometime during summer, not sure exactly when. 
It wasn't a problem earlier, but it has become one now.
![image](https://github.com/WTFender/aws-sso-extender/assets/6637740/a78032fa-f3fd-4c53-9911-87ce682fabc7)
Seems you are hitting the IAM SSO API a bit harder which is then throttled.
If you are hitting the API frequently to update the user list(s) which for most people should be quite static, maybe add an option to not automatically update, but manually update the lists per user. Save the API quota for actual logins.

### Browsers

Chrome

### OS

Windows

**Comment by WTFender** [comment]
Will definitely look into this; not the first rate limiting issue.

Are you seeing this on the AWS console, AWS SSO page or both?

Would you mind sharing how many aws accounts you have associated with your sso user?

**Comment by gomibushi** [comment]
Sorry for the late reply. Looks like I have a total of 50 roles across 37 accounts in the larger org. This is probably edge case high since I am an (security) Admin. Its on the SSO page, but I'm guessing its also why I can't load into a role when I click it from the extension (hangs on the "Signing you in to xxx" page).

**Comment by WTFender** [comment]
I've added basic rate limiting to the AWS SSO page & tested with 35 accounts.

Let me know if the rate limit / 429 errors continue.

**Comment by gomibushi** [comment]
It is a lot better, as in not a problem. 
I have not been getting any more hangs on "Signing you in" the last few days. 
I can still get some errors if I furiously expand the role lists of the accounts on the SSO page, but the first 3-4 do work and you only really need the first list. Great work! Thanks!
