### ISSUE TITLE
Clicking Grafana element doesn't do anything

### ISSUE THREAD

**Issue by santiagolator** [WTFender/aws-sso-extender#79]
### Extension Version

1.6.7

### Description

When clicking on a Grafana element on the list (either on default list or on fav list) doesn't open a new tab. When clicking on an account works fine.

### Browsers

Firefox

### OS

Windows

**Comment by WTFender** [comment]
Thanks for reporting this, I think I'm able to reproduce it.

Do you have firefox containers enabled?

**Comment by santiagolator** [comment]
Hi! Yes, containers are enabled

**Comment by WTFender** [comment]
Just released a version to fix it; let me know if the issue persists.

**Comment by santiagolator** [comment]
Working perfect!
