### ISSUE TITLE
Print Account Name

### ISSUE THREAD

**Issue by oviliz** [WTFender/aws-sso-extender#81]
### Description

The "AWS Account Name" field doesn't appear to be printed to the Console (and Container) and I'm using the "Profile Label & Color" field to fill that in manually. Is there way to get it done by default?
![image](https://github.com/WTFender/aws-sso-extender/assets/73616/3049f12a-05c7-4841-a7e0-255b35f97f7b)

PS. Thanks for your extension @WTFender

**Comment by WTFender** [comment]
@oviliz you're welcome!

Just to clarify, are you saying the label isn't being applied to the AWS console at all or just having trouble with the `{{accountName}}` variable?

The variables don't work in the profile label directly, but I could consider that.

If I wanted `MyPermissionSet @ AccountName` in my console, I would set the profile label as MyPermissionSet and set your "SSO Console label" in the extension settings to be `{{profile}} @ {{accountName}}`.

<img width="611" alt="Screenshot 2023-10-06 at 11 58 44 AM" src="https://github.com/WTFender/aws-sso-extender/assets/12001399/2c475f0d-cb3f-4bac-a4a8-e76f822c7bca">

<img width="400" alt="Screenshot 2023-10-06 at 11 58 44 AM" src="https://github.com/WTFender/aws-sso-extender/assets/12001399/451fa8ea-9768-4b8e-bd45-6437fe61c61e">

<img width="400" alt="Screenshot 2023-10-06 at 2 54 10 PM" src="https://github.com/WTFender/aws-sso-extender/assets/12001399/99d2232f-a7a8-4487-977c-56657fa4465e">

**Comment by oviliz** [comment]
Oh, I didn't realise I could do that from the SSO Console Label. Thank you sir.
