### ISSUE TITLE
Hotkey, faster keyboard navigation

### ISSUE THREAD

**Issue by gomibushi** [WTFender/aws-sso-extender#83]
### Description

Hi, I'm back again. :)

I had an idea for further small improvements to the already excellent extension.

How about a keyboard shortcut? If that is at all possible with chrome extensions.
A ctrl+<key>, or ctrl+shift+<key> would be nice.

And a second and third suggestion that should at least be possible, and also in the theme of keyboard navigation.
When the extension is opened I'd prefer to be dropped into the search box, not two tabs away.
When I have typed 3-4 letters in the search box I will have 1-3 roles/accounts in the list. It would be really nice to just be able to either tab through them or perhaps arrow down/arrow up navigate from the search box.

**Comment by WTFender** [comment]
I just fixed the searchbox so that it autofocuses; I must have broke that at some point.

I was thinking of doing hotkeys the first 5 profiles in view / search results. You can open any extension with a hotkey already (chrome://extensions/shortcuts) & I'd probably have you set the bind keys there.

**Comment by gomibushi** [comment]
Didn't know about the chrome extension shortcuts, obviously. And the search box focus works already in 1.6.10. Excellent! Thanks!
Its already a lot smoother to use.

**Comment by WTFender** [comment]
@gomibushi in 1.7.0 you can browse the profiles with up/down arrows and Enter to open that profile - hope it helps!

Also, you can link up to 3 profiles to your own hotkeys:
<img width="400" alt="image" src="https://github.com/WTFender/aws-sso-extender/assets/12001399/59ef22c3-819f-4e52-97d3-93ca4ce935b0">


On Firefox, those profile hotkeys are smart enough to switch between already open tabs/containers.
