### ISSUE TITLE
No profiles/accounts detected for SS0

### ISSUE THREAD

**Issue by slimam** [WTFender/aws-sso-extender#86]
### Extension Version

1.7.0

### Description

After installing the plugin i have no profiles/accounts listed, the user is set to No ? and it cant detect any account/profile

My sso login url is in this format :

https://d-XXXXXX.awsapps.com/start#/

### Browsers

Chrome

### OS

Windows

**Comment by WTFender** [comment]
@slimam the extension should properly find your existing aws sso directory links now.

Lmk if you're still having trouble
