### ISSUE TITLE
No profiles detected

### ISSUE THREAD

**Issue by WTFender** [WTFender/aws-sso-extender#87]
### Extension Version

?

### Description

https://twitter.com/xelfer/status/1724964408450068499

### Browsers

Chrome

### OS

Windows

**Comment by NGAJean** [comment]
Same issue on Microsoft Edge : No login links found in browser history.

**Comment by WTFender** [comment]
I haven't been able to reproduce this reliably enough to fix it, but it's definitely an issue.

@NGAJean could you share any more details?

Did you see this randomly, after installing, after updating, etc?

Approximately how many accounts/profiles are you working with?
