### ISSUE TITLE
Allow Renaming of User

### ISSUE THREAD

**Issue by hreeder** [WTFender/aws-sso-extender#92]
### Description

I have access to two different directories that I use regularly with aws-sso-extender, but when swapping between them I have to choose from the list like:
- {email} @ d-123456abcdef
- {email} @ d-654321fedcba

I'd love to have something in the settings (even if I need to edit the config and add it at `users[].custom.displayName` or similar) that would allow me to set the name for these, so that I'm maybe choosing from:
- {email} @ Contoso
- {email} @ Example Corp

**Comment by WTFender** [comment]
Makes sense & seems simple, I'll see what I can do soon.

Also wanted to mention that you can display multiple users profile at once and it will have this "shared icon" if it's from the not currently selected user - pretty quick way to use profiles from multiple users without having to switch.

<img width="500" alt="Screenshot 2023-12-05 at 8 11 10 AM" src="https://github.com/WTFender/aws-sso-extender/assets/12001399/5b267560-4b13-4309-a155-e6aa8aa276f7">

**Comment by WTFender** [comment]
@hreeder FYI this was added!

Let me know if you run into issues.

<img width="500" alt="image" src="https://github.com/WTFender/aws-sso-extender/assets/12001399/6e77afd3-654d-4e05-86d8-9451923f4efe">
