### ISSUE TITLE
Incorrect tab change with multiple browser windows on Firefoy

### ISSUE THREAD

**Issue by iptizer** [WTFender/aws-sso-extender#96]
### Extension Version

1.7.6

### Description

Steps to reproduce:
* Start Firefox. Create 2 browser Windows.
* In browser Window A: Start 5 tabs (sth. doesn't matter).
* In browser Window B: Start 2 tabs.
* In browser Window B: Login to an AWS Account with extension. (AWS Console is now on 3rd tab.)
* In browser Window A: Login to the same Account using extension.
* Behavior: The extension switches to the third tab in the current browser window. Seems like the extension ignores the browser Window information.

=> Not sure whether this is fixable with switching to the other browser window. But this would be the expected output, but it might also be confusing, as the other window may be on a completely different screen.

### Browsers

Firefox

### OS

Mac

**Comment by WTFender** [comment]
Good find, this should be fixed now.
