### ISSUE TITLE
Roles from more than one organization doesn't show any more

### ISSUE THREAD

**Issue by gomibushi** [WTFender/aws-sso-extender#98]
### Extension Version

1.7.6

### Description

Not sure when it started as I'm 95% on the one organization.
Now I have to switch between users/orgs, the "Show All Profiles On Open" doesn't seem to show all profiles/roles, just the selected one.
I have 3 chrome profiles for simultanious multi-account work and all of them show this behviour.
I have tried the "reset all iam profiles" button and logged on to the start-portal for each org, but didn't change anything.

### Browsers

Chrome

### OS

Windows

**Comment by WTFender** [comment]
'Show All Profiles on Open' is for when you don't want the list filtered to your favorite profiles by default.

Edit the profile list & check 'All Users' to show profiles from all users.

The settings in general are not super clear, I'll see what I can do in the next version.

![image](https://github.com/WTFender/aws-sso-extender/assets/12001399/946d1fbb-080d-4393-875a-c0d9e6ef21df)

**Comment by gomibushi** [comment]
Thank you, and sorry for being an idiot.
BUT the UI should be a bit more idiot proof though. :)
In my mind this setting makes sense to put in the Users tab where you can switch users, which is a related to showing profiles from all users.
Again, thanks for the tool I use daily! (And still haven't learned)
